# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Subtitulo', models.CharField(max_length=50)),
                ('Imagen', models.FileField(blank=True, upload_to='media/fotos/noticias')),
                ('SubtituloImag', models.CharField(max_length=30)),
                ('Cuerpo', models.CharField(max_length=500)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Lugar', models.CharField(max_length=50)),
                ('Dia', models.DateTimeField()),
                ('Hora', models.CharField(max_length=5)),
                ('Organizadores', models.CharField(max_length=30)),
                ('Ponente', models.CharField(max_length=30)),
                ('Tags', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Subtitulo', models.CharField(max_length=50)),
                ('Imagen', models.FileField(blank=True, upload_to='media/fotos/noticias')),
                ('SubtituloImag', models.CharField(max_length=30)),
                ('Cuerpo', models.TextField(max_length=500)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Estado', models.CharField(choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador')], default='Borrador', max_length=9)),
                ('IncluirVideo', models.BooleanField()),
                ('CodVideo', models.CharField(max_length=200)),
                ('Tags', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
