# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdiccionTic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Hora',
        ),
    ]
