# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdiccionTic', '0002_remove_evento_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Dia',
            new_name='Fecha',
        ),
    ]
