# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdiccionTic', '0003_auto_20160816_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artista', models.CharField(max_length=30)),
                ('TituloAlbum', models.CharField(max_length=50)),
                ('Genero', models.FileField(blank=True, upload_to='media/fotos/noticias')),
                ('LogoAlbum', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoArchivo', models.CharField(max_length=10)),
                ('tituloCancion', models.CharField(max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdiccionTic.Album')),
            ],
        ),
    ]
