# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdiccionTic', '0004_album_cancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Artista',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='album',
            name='Genero',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='album',
            name='LogoAlbum',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='album',
            name='TituloAlbum',
            field=models.CharField(max_length=500),
        ),
    ]
